### ISSUE TITLE
[Substance] Focus problem when switching from a JTable to a nearby Jbutton

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#218] opened 2019-11-06 09:59 UTC
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
When switching from a column of a JTable to a nearby Jbutton, focus on the column 
is not lost sometimes, although the column is not selected. 

This phenomenon seems to occur randomly for different JTables, but definitely for 
a specific JTable, i.e. the same phenomenon can be observed for the same JTable, 
for example, a JTable has 26 rows with a vertical scrollbar.

**Comment by kirill-grouchnikov** [comment] 2019-11-06 15:33
I can't seem to be able to reproduce this, perhaps because some details are missing. Can you attach a small reproducible case where this is happening in 3.0-SNAPSHOT?

**Comment by kirill-grouchnikov** [comment] 2019-11-22 23:23
Closing since there was no comment in the last two weeks.

**Closed by kirill-grouchnikov** 2019-11-22 23:23 UTC
Labels: 3.0 - Diamond

**Comment by kirill-grouchnikov** [comment] 2020-02-08 14:21
See https://github.com/kirill-grouchnikov/radiance/issues/236
