### ISSUE TITLE
[Substance] Maximize bug on secondary screen when screen resolutions differ

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#3] opened 2018-05-23 18:54 UTC
This one is an old one, but it's still present on latest version.

You need two monitors with different screen sizes. Set the screen size for the secondary monitor bigger than the primary monitor. For example:

    Screen 1: 1366x768
    Screen 2: 1920x1080

Steps to reproduce:

    Run an empty JFrame with Substance L&F, it must be opened by default on Screen 1.
    Drag the window to the Screen 2.
    Maximize.

Expected: Window having full size on Screen 2.
Actual: Window is correctly positioned on (0,0) but the frame size is equal to Screen 1 size, so it does not cover the full screen.

**Comment by PirolA** [comment] 2020-01-10 12:06
I'll be nice to get a fix for this issue :)

**Comment by kirill-grouchnikov** [comment] 2020-01-10 13:40
Copying from the original Substance bug report.

As far as multi-window setups go, I would have to defer fixing such bugs to people who are experiencing them, as I don't have a setup like that available to me.

Specifically, if you are running under decorated mode, it is handled by SubstanceTitlePane.MaximizeAction.actionPerformed. In addition to what MetalTitlePane.MaximizeAction.actionPerformed does, it also calls SubstanceRootPaneUI.setMaximized.

That method queries the graphics configuration of that app window and calls setMaximizedBounds on the matching JFrame. Not sure how this works for decorated Metal windows without that path though.

**Comment by nroduit** [comment] 2020-02-16 08:22
I tried to analyze this problem because it is really annoying when using 2 screens on Windows.

Historically, there was a bug in the JVM, where the window hides the windows bar (described [here](https://stackoverflow.com/questions/6422931/why-jframe-hides-taskbar-when-maximized/6422987#6422987)):
* from 1.4 to 1.6: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4737788
* "fixed" in 1.7b121: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6699851

And now a different bug from version Java 9 to 14 (fixed in 15): https://bugs.openjdk.java.net/browse/JDK-8231564

The bug can be reproduced virtually with VirtualBox and Windows 10 as guest + 2 virtual screens.
The only configuration that works correctly is when both screens have the same resolution and scale at 100%, all other configurations fail. Even maximizing the window on the first screen with 
display scale larger 100%.

I post a [PR](https://github.com/kirill-grouchnikov/radiance/pull/243). Removing the maximized bound (and only using setExtendedState(state | JFrame.MAXIMIZED_BOTH)) seems to be the right solution because hiding the Window bar has been fixed from Java 7 and Radiance works with Java 9 and superior. With this fix, I haven't found any issue.

**Comment by kirill-grouchnikov** [comment] 2020-02-18 20:35
Well, let's get this in and see if there's any regression being reported.

**Closed** 2020-02-18 20:38 UTC
Labels: 3.0 - Diamond
