### ISSUE TITLE
Exception on Show/Hide Ribbon and Ribbon is not showing up

### ISSUE THREAD

**Issue by suhasinisridhar** [kirill-grouchnikov/radiance#346] opened 2021-06-10 18:55 UTC
### Version of OS(Windows 10)

 I am getting below exception on Show/Hide Ribbon at times and the Ribbon doesn't show up

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "org.pushingpixels.flamingo.api.common.model.CommandMenuContentModel.getCommandGroups()" because "this.popupMenuContentModel" is null
at org.pushingpixels.flamingo.api.common.popup.JCommandPopupMenu.populateContent(JCommandPopupMenu.java:111)
at org.pushingpixels.flamingo.api.common.popup.JCommandPopupMenu.<init>(JCommandPopupMenu.java:88)
at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$GlobalPopupMenu.<init>(JRibbonFrame.java:663)
at org.pushingpixels.flamingo.api.common.projection.Projection.buildComponent(Projection.java:138)
at org.pushingpixels.flamingo.api.common.projection.AbstractPopupMenuProjection.buildComponent(AbstractPopupMenuProjection.java:49)
at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame.handlePopupTrigger(JRibbonFrame.java:745)
at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame.access$400(JRibbonFrame.java:89)
at org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$1.eventDispatched(JRibbonFrame.java:480)
at org.pushingpixels.substance.api.SubstanceLookAndFeel.lambda$initialize$0(SubstanceLookAndFeel.java:226)

**Comment by kirill-grouchnikov** [comment] 2021-06-10 19:19
This is due to a null `CommandMenuContentModel` returned from `getContextualMenuContentModel()` of your `JRibbon.setOnShowContextualMenuListener` on one of the elements in your ribbon. If you set that listener, it needs to return a non-null menu content model.

Certainly might be a bug in Flamingo / Radiance. If this can be reproduced in the main `BasicCheckRibbon`, I'll need to see the exact sequence of steps. Otherwise, start in your ribbon contextual menu listener logic to verify that you never return a null menu content model.

**Comment by kirill-grouchnikov** [comment] 2021-06-14 20:03
Closing this as there is no comment beyond the original report.

**Closed as completed by kirill-grouchnikov** 2021-06-14 20:03 UTC
