### ISSUE TITLE
Limitation of Java Version for build

### ISSUE THREAD

**Issue by nroduit** [kirill-grouchnikov/radiance#244] opened 2020-02-16 08:39 UTC
The version of Java defined in Substance is not consistent with the source code that contains language elements from version 9. This [line](https://github.com/kirill-grouchnikov/radiance/blob/master/substance/build.gradle#L38) should be removed, and let the default value from parent (currently 9).

Also, I don't understand why the build has to fail when you don't use a JDK 9 (defined [here](https://github.com/kirill-grouchnikov/radiance/blob/master/build.gradle#L77)). compileJava.doFirst should be removed to let, for instance, compiling Java 9 classes (byte code in Java 9) with a JDK 11 or superior.

**Comment by kirill-grouchnikov** [comment] 2020-02-16 17:48
I'll remove that line.

As for building with JDK 9, I want to make sure that nothing from later versions of the language - language features, as well as newer APIs - gets into the binaries.

**Comment by kirill-grouchnikov** [comment] 2020-02-16 17:49
Wait, you're referencing build.gradle from the long-archived Substance. The build file from Radiance defines both source and target compatibility to be the same as the java version.

**Comment by nroduit** [comment] 2020-02-16 18:16
``` bash
def javaVersion = JavaVersion.VERSION_1_9
sourceCompatibility = javaVersion #means the version compatibility with the java source file (.java)
targetCompatibility = javaVersion #means the version compatibility with the generate byte code (.class)
```
In most case, the value of the source and the target must be the same (different values can fail).

The following code limits to the exclusive use of JDK 9 whereas by removing this code a JDK 11 could be used while preserving the compatibility of the language (9 with sourceCompatibility) and the compatibility of the generated classes (9 with targetCompatibility).
``` bash
        compileJava.doFirst {
            if (JavaVersion.current() != javaVersion)
                throw new IllegalStateException("Compiler version mismatch; required is "
                        + javaVersion + ", but using " + JavaVersion.current());
        }
```

**Comment by nroduit** [comment] 2020-02-16 18:18
In practice, almost nobody uses JDK 9 and 10 anymore.

**Comment by kirill-grouchnikov** [comment] 2020-02-16 19:55
I want to have hermetically reproducible builds on my machine that don't change when I install any of the latest JDKs for testing at runtime. 

As for the distribution numbers for 9 or 10, that's not enough of a reason to bump up the minimum requirements. I haven't seen any language feature or API enhancement so far that would justify going away from 9.

**Comment by kirill-grouchnikov** [comment] 2020-02-18 21:12
Closing this since my preference is to use the same JDK for local builds as the one that is the minimum runtime target.

**Closed by kirill-grouchnikov** 2020-02-18 21:12 UTC

**Comment by nroduit** [comment] 2020-02-20 14:37
Sorry to insert two points in this issue but the first one is a real problem where it specifies `sourceCompatibility = 1.8` while the Java source files contain elements of Java 9. There are no errors at compile time as these are language elements linked to the anonymous classes and generics. 

For the second point, building with JDk9 or JDK 11 and the specification of the source and target to 1.9 will produce the same .class.

**Comment by kirill-grouchnikov** [comment] 2020-02-20 14:41
The `sourceCompatibility = 1.8` is from the old Substance repository that is archived and is no longer under any development. All new development has been happening in the main Radiance repository for quite some time now.

As for the second point, my current preference is to build with the same JDK that is the minimum runtime version. The binaries are published on Maven and are available for download as part of the repository. People who wish to build Radiance locally can install Java 9 from the official download archives of the JDK following a simple search.

**Comment by kirill-grouchnikov** [comment] 2020-02-20 14:42
Just noticed that your first comment is correct. My apologies. I did not remove that line from the Substance module build.gradle. Will do today.

**Comment by nroduit** [comment] 2020-02-20 14:45
OK, Thanks.

**Comment by kirill-grouchnikov** [comment] 2020-02-21 00:06
`sourceCompatibility = 1.8` has been removed from the build files
