### ISSUE TITLE
[Gradle] SVG Transcoder run error

### ISSUE THREAD

**Issue by VincentYoung33** [kirill-grouchnikov/radiance#449] opened 2023-05-12 03:49 UTC
### Version of Radiance (latest release is 7.0-SNAPSHOT)
Transcode plugin verison: 6.5.0
### Version of Java (current minimum is 9)
Java 9
### Version of OS
Windows
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
**My project structure is :**
![image](https://github.com/kirill-grouchnikov/radiance/assets/95176568/8152948e-4d92-413e-aba2-ecfa6d30687f)

**My gradle build.script is :**
`buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.pushing-pixels:radiance-svg-transcoder-gradle-plugin:6.5.0'
    }
}

plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

apply plugin: 'org.pushing-pixels.radiance.tools.svgtranscoder.gradle'

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'org.pushing-pixels:radiance-common:6.5.0'
}

compileJava.doFirst {
    transcode {
        inputDirectory =  file('src/main/resources')
        outputDirectory = file('src/main/java/org/radiance/demo/svg')
        outputLanguage = 'java'
        outputPackageName = 'org.radiance.demo.svg'
        transcode()
    }
}
test {
    useJUnitPlatform()
}
`
When I run 'transcode' , the error occurs: 

**Some problems were found with the configuration of task ':transcode' (type 'TranscodeTask').
  - Type 'org.pushingpixels.radiance.tools.svgtranscoder.gradle.TranscodeTask' property 'inputDirectory' doesn't have a configured value.**

I google it but it doesn't work.

**Comment by kirill-grouchnikov** [comment] 2023-05-12 04:17
Does the note at https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/tools/svg-transcoder/svg-transcoder-gradle-plugin.md#additional-notes-1 apply to your case?

If not, and you do have some real Java classes in there (which your screenshot does not show, by the way), I'll need to see a complete zip file of this sample project attached here in this bug.

**Comment by VincentYoung33** [comment] 2023-05-12 05:19
It seems that the note at https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/tools/svg-transcoder/svg-transcoder-gradle-plugin.md#additional-notes-1 doesn't apply to my case.
I don't have some real Java classes, but can the svg transcoder transcode the svg to java class? I'm confused about it.
The complete zip file of this sample project is here.
[groovytests.zip](https://github.com/kirill-grouchnikov/radiance/files/11459283/groovytests.zip)

**Comment by VincentYoung33** [comment] 2023-05-12 08:44
Do I misunderstand the use of svg transcoder with gradle? @kirill-grouchnikov

**Comment by kirill-grouchnikov** [comment] 2023-05-12 12:28
That's what that note is about. The sample Gradle task of `compileJava.doFirst` is not going to run if you don't have any Java sources in there to begin with.

https://github.com/kirill-grouchnikov/radiance-svg-transcoder-plugin-test is the full sample that includes a simple test Java class.

There probably is another way to configure a custom Gradle task to run Radiance SVG transcoder before regular Java / Kotlin compilation even if there are no other Java / Kotlin sources in the project. At the present moment this is beyond my knowledge of Gradle, and beyond the scope of Radiance itself. If you find a Gradle task suited for this particular case, I'll be happy to include that in the documentation.

Closing this as this is not a bug in Radiance, but rather a more generic question on Gradle.

**Closed as completed by kirill-grouchnikov** 2023-05-12 12:28 UTC

**Comment by VincentYoung33** [comment] 2023-05-12 13:06
Thanks a lot! You are really warm-hearted
